### ISSUE TITLE
Strange sound after start

### ISSUE THREAD

**Issue by AcTiViSioN911** [danskee/Memory-Cleaner#3]
Hello. I have an MSI GL63 laptop with a 9750H and an RTX 2060. When I press the Start button, I start to hear a whistle, something like the whistle of the video card throttles. When I press Stop, the sound stops. I don't think this is normal. Can you explain why this is happening?

**Comment by danskee** [comment]
The default timer resolution on Windows is ~15.6 ms which means that there's a timer interrupt 64 times a second. When you set it to for example 0.5ms, there will be a timer interrupt 2000 times a second which increases power consumption and harms battery life.
